#!/bin/bash

# Allow your own connection
sudo iptables -A INPUT -s 172.31.18.211 -j ACCEPT       #Adding  your Private IPv4 address


# Flush existing rules and set default policies to DROP
#sudo iptables -F                        #-F command clears all existing rules from the iptables configuration
#sudo iptables -P INPUT DROP             # -P command set the default behavior for traffic that doesn't match any specific rule. Incoming traffic that doesn't match any rule is dropped by default
#sudo iptables -P FORWARD DROP           # Traffic forwarded through the server is dropped by defaul
sudo iptables -P OUTPUT ACCEPT          # Outgoing traffic is allowed by default
sudo iptables -P INPUT ACCEPT

# Allow loopback traffic                        # These rules allow loopback traffic, which is necessary for local communication between processes on the server itself
sudo iptables -A INPUT -i lo -j ACCEPT
sudo iptables -A OUTPUT -o lo -j ACCEPT

# Allow established and related connections              # This rule allows incoming traffic that is part of an established or related connection
sudo iptables -A INPUT -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT




# 1. Allow incoming connections to port 25 (SMTP) from the internet         # Port 25: This is the standard port for SMTP (Simple Mail Transfer Protocol), which is used for sending emails
sudo iptables -A INPUT -p tcp --dport 25 -j ACCEPT                          # By allowing incoming connections on this port, you are permitting your mail server to receive emails from the internet


# 2. Allow outbound DNS connections (port 53 TCP/UDP) to AWS DNS servers           # Port 53: This is the standard port for DNS (Domain Name System) requests, used to resolve domain names to IP addresses
sudo iptables -A OUTPUT -p udp --dport 53 -d AmazonProvidedDNS_IP -j ACCEPT
sudo iptables -A OUTPUT -p tcp --dport 53 -d AmazonProvidedDNS_IP -j ACCEPT

# 3. Close all connections to port 143 (IMAP)              # Port 143: This is the standard port for IMAP (Internet Message Access Protocol), which is used for retrieving email messages from a mail server
sudo iptables -A INPUT -p tcp --dport 143 -j DROP
sudo iptables -A OUTPUT -p tcp --dport 143 -j DROP               #  By dropping incoming connections on this port, you are preventing external access to your mail server via the less secure IMAP protocol

# 4. Allow incoming connections to port 993 (IMAPS) for HR department (192.168.42.150-199) and Backup server (192.168.42.250)       # Port 993: This is the secure IMAP port (IMAPS) used for encrypted email access
sudo iptables -A INPUT -s 192.168.42.150/29 -p tcp --dport 993 -j ACCEPT        # By allowing all connections on this port from specific IP ranges, you are granting access to the HR department and the Backup server to securely retrieve email messages
sudo iptables -A INPUT -s 192.168.42.250 -p tcp --dport 993 -j ACCEPT

# 5. Allow incoming connections to port 465 (SMTPS) for IT department (192.168.42.200-220) only          # Port 465: This is the secure SMTP port (SMTPS) used for sending emails over a secure connection
sudo iptables -A INPUT -s 192.168.42.200/28 -p tcp --dport 465 -j ACCEPT                            # By allowing incoming connections on this port from a specific IP range, you are permitting the IT department to send emails securely

# 6. Allow incoming connections to port 587 (SMTP) for HR department (192.168.42.150-199) and IT department (192.168.42.200-220) only        # Port 587: This is another SMTP port used for sending emails
sudo iptables -A INPUT -s 192.168.42.150/29 -p tcp --dport 587 -j ACCEPT                # By allowing incoming connections on this port from specific IP ranges, you are permitting both the HR and IT departments to send emails
sudo iptables -A INPUT -s 192.168.42.200/29 -p tcp --dport 587 -j ACCEPT

# 7. Allow incoming SMB connections (assuming SMB uses ports 137-139) from the Backup server each evening       # Ports 137-139: These are commonly used by the SMB (Server Message Block) protocol for file and printer sharing
sudo iptables -A INPUT -s 192.168.42.250 -p tcp -m multiport --sports 137:139 -m time --timestart 18:00 --timestop 21:00 -j ACCEPT   # By allowing incoming connections on these ports from the Backup server, you enable file backup operations from 18:00h to 21:00h everyday
sudo iptables -A INPUT -s 192.168.42.250 -p udp -m multiport --sports 137:139 -m time --timestart 18:00 --timestop 21:00 -j ACCEPT

# 8. Allow SSH access (default port 22) for IT department (192.168.42.200-220)          # Port 22: This is the default SSH (Secure Shell) port, which is used for remote server administration
sudo iptables -A INPUT -s 172.31.18.211/32 -p tcp --dport 22 -j ACCEPT                  # By allowing incoming SSH connections on port 22 from a specific IP range, you grant the IT department secure access to the server


# 9. Restrict all other incoming connections (except port 443)
sudo iptables -A INPUT -p tcp --dport 443 -j ACCEPT         # These rules restrict all other incoming connections, except for HTTPS (port 443)
sudo iptables -A INPUT -j DROP                              # Any incoming traffic that does not match any of the previous rules will be dropped by the last rule (DROP)

# Checking is everything is working:
sudo iptables -L -n
sudo iptables -L






#iptables: This is the command for managing the Linux kernel's netfilter firewall subsystem
